---
title: "Data_Visualization_Part_2"
output: github_document
date: "2023-03-13"
---

```{r steup, message=FALSE}
library(tidyverse)
library(patchwork)
```


```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```


## last session plot

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5)
```

## Labels
```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    title = "Tempreture Plot",
    x = "Minimum temp per day (c)",
    y = "Maximum temp per day (c)",
    caption = "Data from rnoaa package"
  )
```

## Scales

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    title = "Tempreture Plot",
    x = "Minimum temp per day (c)",
    y = "Maximum temp per day (c)",
    caption = "Data from rnoaa package"
  ) +
  scale_x_continuous(
    breaks = c(-15, 0, 15),
    labels = c("-15 C", "0", "15 C")
  ) +
  scale_y_continuous(
    trans = "sqrt"
  )
```

sqrt for long tail
or log


Look at color scales

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    title = "Tempreture Plot",
    x = "Minimum temp per day (c)",
    y = "Maximum temp per day (c)",
    caption = "Data from rnoaa package"
  ) +
  scale_color_hue( name = "Location" ,h = c(100,300))
```

Package viridis for color manipulation

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    title = "Tempreture Plot",
    x = "Minimum temp per day (c)",
    y = "Maximum temp per day (c)",
    caption = "Data from rnoaa package"
  ) +
  viridis::scale_color_viridis(
    discrete = TRUE,
    name = "location"
  )
```

